# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created: Tue Aug 26 12:38:00 2014
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Add(object):
    def setupUi(self, Add):
        Add.setObjectName(_fromUtf8("Add"))
        Add.resize(402, 768)
        self.AddBut = QtGui.QPushButton(Add)
        self.AddBut.setGeometry(QtCore.QRect(250, 50, 101, 27))
        self.AddBut.setObjectName(_fromUtf8("AddBut"))
        self.name = QtGui.QLineEdit(Add)
        self.name.setGeometry(QtCore.QRect(50, 50, 181, 31))
        self.name.setObjectName(_fromUtf8("name"))
        self.label = QtGui.QLabel(Add)
        self.label.setGeometry(QtCore.QRect(50, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Add)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.office = QtGui.QLineEdit(Add)
        self.office.setGeometry(QtCore.QRect(50, 130, 181, 31))
        self.office.setObjectName(_fromUtf8("office"))
        self.cell = QtGui.QLineEdit(Add)
        self.cell.setGeometry(QtCore.QRect(50, 210, 181, 31))
        self.cell.setText(_fromUtf8(""))
        self.cell.setObjectName(_fromUtf8("cell"))
        self.label_3 = QtGui.QLabel(Add)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.home = QtGui.QLineEdit(Add)
        self.home.setGeometry(QtCore.QRect(50, 290, 181, 31))
        self.home.setText(_fromUtf8(""))
        self.home.setObjectName(_fromUtf8("home"))
        self.label_4 = QtGui.QLabel(Add)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pref = QtGui.QLineEdit(Add)
        self.pref.setGeometry(QtCore.QRect(50, 430, 181, 31))
        self.pref.setText(_fromUtf8(""))
        self.pref.setObjectName(_fromUtf8("pref"))
        self.label_5 = QtGui.QLabel(Add)
        self.label_5.setGeometry(QtCore.QRect(50, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.notes = QtGui.QLineEdit(Add)
        self.notes.setGeometry(QtCore.QRect(50, 510, 181, 31))
        self.notes.setText(_fromUtf8(""))
        self.notes.setObjectName(_fromUtf8("notes"))
        self.label_6 = QtGui.QLabel(Add)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Add)
        self.label_7.setGeometry(QtCore.QRect(50, 560, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.grop = QtGui.QLineEdit(Add)
        self.grop.setGeometry(QtCore.QRect(50, 590, 181, 31))
        self.grop.setText(_fromUtf8(""))
        self.grop.setObjectName(_fromUtf8("grop"))
        self.label_8 = QtGui.QLabel(Add)
        self.label_8.setGeometry(QtCore.QRect(50, 640, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.supervisor = QtGui.QLineEdit(Add)
        self.supervisor.setGeometry(QtCore.QRect(50, 670, 181, 31))
        self.supervisor.setText(_fromUtf8(""))
        self.supervisor.setObjectName(_fromUtf8("supervisor"))
        self.Delete = QtGui.QPushButton(Add)
        self.Delete.setGeometry(QtCore.QRect(250, 110, 101, 27))
        self.Delete.setObjectName(_fromUtf8("Delete"))
        self.Update = QtGui.QPushButton(Add)
        self.Update.setGeometry(QtCore.QRect(250, 80, 101, 27))
        self.Update.setObjectName(_fromUtf8("Update"))
        self.label_9 = QtGui.QLabel(Add)
        self.label_9.setGeometry(QtCore.QRect(50, 330, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pager = QtGui.QLineEdit(Add)
        self.pager.setGeometry(QtCore.QRect(50, 360, 181, 31))
        self.pager.setText(_fromUtf8(""))
        self.pager.setObjectName(_fromUtf8("pager"))

        self.retranslateUi(Add)
        QtCore.QMetaObject.connectSlotsByName(Add)
        Add.setTabOrder(self.name, self.office)
        Add.setTabOrder(self.office, self.cell)
        Add.setTabOrder(self.cell, self.home)
        Add.setTabOrder(self.home, self.pager)
        Add.setTabOrder(self.pager, self.pref)
        Add.setTabOrder(self.pref, self.notes)
        Add.setTabOrder(self.notes, self.grop)
        Add.setTabOrder(self.grop, self.supervisor)
        Add.setTabOrder(self.supervisor, self.AddBut)
        Add.setTabOrder(self.AddBut, self.Update)
        Add.setTabOrder(self.Update, self.Delete)

    def retranslateUi(self, Add):
        Add.setWindowTitle(_translate("Add", "Phone Tool Database Updater", None))
        self.AddBut.setText(_translate("Add", "Add", None))
        self.AddBut.setShortcut(_translate("Add", "Ctrl+A", None))
        self.label.setText(_translate("Add", "Name:", None))
        self.label_2.setText(_translate("Add", "Office Extension:", None))
        self.label_3.setText(_translate("Add", "Cell:", None))
        self.label_4.setText(_translate("Add", "Home:", None))
        self.label_5.setText(_translate("Add", "Preference:", None))
        self.label_6.setText(_translate("Add", "Notes:", None))
        self.label_7.setText(_translate("Add", "Group:", None))
        self.label_8.setText(_translate("Add", "Supervisor:", None))
        self.Delete.setText(_translate("Add", "Delete", None))
        self.Update.setText(_translate("Add", "Update", None))
        self.label_9.setText(_translate("Add", "Pager", None))

